language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r webserver/requirements.txt --use-mirrors"
# command to run tests
script: cd webserver && python -m unittest discover
