CREATE TABLE clients (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value INTEGER,
  time INTEGER
);

CREATE TABLE temperature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value INTEGER,
  time INTEGER
);

CREATE TABLE door (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value BOOLEAN,
  time INTEGER
);
